services:
  mysql:
    image: mysql:8.0
    container_name: bibliotheque-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bibliotheque_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
